{
gROOT->SetBatch(1);
double xmax = 4;
double xmin = -0.5;
double ymin=xmin;
double ymax=xmax;
gROOT->ProcessLine(".x ~/scripts/root_palette.C");
hall->GetYaxis()->SetRangeUser(ymin,ymax);
hall->GetXaxis()->SetRangeUser(xmin,xmax);
hall->SetTitle("");
hall->GetXaxis()->SetTitle("#mu_{ttH+ggH}");
hall->GetYaxis()->SetTitle("#mu_{VH+qqH}");
hall->SetMaximum(10);
TH2F *h68 = (TH2F*)hall->Clone();
 TH2F *h95 = (TH2F*)hall->Clone();
h68->SetContour(2);
h95->SetContour(2);
h68->SetContourLevel(1,2.3);
h95->SetContourLevel(1,5.99);
h95->SetLineColor(1);
h68->SetLineColor(1);
TLine LH(xmin,1,xmax,1);
TLine LV(1,ymin,1,ymax);
LH.SetLineStyle(2);
LV.SetLineStyle(2);
TCanvas *c = new TCanvas("c","",500,500);
hall->Draw("col");
LH.Draw();
LV.Draw();
h95->SetLineStyle(2);
h68->Draw("cont3same");
h95->Draw("cont3same");
TLatex *lat = new TLatex();
lat->SetNDC();
lat->SetTextFont(42);
lat->SetTextSize(0.035);
lat->DrawLatex(0.1,0.92,"CMS Preliminary");
TLegend *leg = new TLegend(0.7,0.7,0.88,0.88);
leg->SetFillColor(10);
leg->SetTextFont(42);
leg->AddEntry(h68,"68% CL","L");
leg->AddEntry(h95,"95% CL","L");
leg->Draw();
c->SaveAs("rvrf.pdf");
c->SaveAs("rvrf.png");

TCanvas *d = new TCanvas("c","",500,500);
hall->Draw("AXIS");
LH.Draw();
LV.Draw();
h68->Draw("cont3same");
h95->Draw("cont3same");
lat->DrawLatex(0.1,0.92,"CMS Preliminary");
//leg->SetFillColor(10);
//leg->SetTextFont(42);
//leg->AddEntry(h68,"68% CL","L");
//leg->AddEntry(h95,"95% CL","L");
leg->Draw();
d->SaveAs("rvrf-nocol.pdf");
d->SaveAs("rvrf-nocol.png");
}
